### ISSUE TITLE
cannot compiler while npm install

### ISSUE THREAD

**Issue by Cheny-chen** [holepunchto/sodium-native#101]
How to fix the problem
#56  doesn't help me to solve this issue

make: *** [Release/obj.target/sodium/binding.o] Error 1
make: Leaving directory `/var/www-host/blockchain-authority-stellar/node_modules/sodium-native/build'

```
In file included from ../src/crypto_pwhash_async.cc:2:0,
                 from ../binding.cc:12:
../src/macros.h:66:46: error: no matching function for call to ‘v8::Value::ToObject()’
   v8::Local<v8::Object> var = name->ToObject();
                                              ^
../binding.cc:1246:5: note: in expansion of macro ‘ASSERT_BUFFER’
     ASSERT_BUFFER(info[2], tag)
     ^
../src/macros.h:66:46: note: candidates are:
   v8::Local<v8::Object> var = name->ToObject();
                                              ^
../binding.cc:1246:5: note: in expansion of macro ‘ASSERT_BUFFER’
     ASSERT_BUFFER(info[2], tag)
     ^
In file included from /root/.node-gyp/12.4.0/include/node/node.h:63:0,
                 from ../binding.cc:1:
/root/.node-gyp/12.4.0/include/node/v8.h:2532:44: note: v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^
/root/.node-gyp/12.4.0/include/node/v8.h:2532:44: note:   candidate expects 1 argument, 0 provided
In file included from /root/.node-gyp/12.4.0/include/node/v8-internal.h:14:0,
                 from /root/.node-gyp/12.4.0/include/node/v8.h:25,
                 from /root/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../binding.cc:1:
/root/.node-gyp/12.4.0/include/node/v8.h:2546:35: note: v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^
/root/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^
/root/.node-gyp/12.4.0/include/node/v8.h:2546:35: note:   candidate expects 1 argument, 0 provided
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^
/root/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../src/crypto_pwhash_async.cc:2:0,
                 from ../binding.cc:12:
../binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE crypto_secretstream_xchacha20poly1305_rekey(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/macros.h:123:60: error: no matching function for call to ‘v8::Value::ToObject()’
   type* var = Nan::ObjectWrap::Unwrap<type>(name->ToObject());
                                                            ^
../binding.cc:1258:3: note: in expansion of macro ‘ASSERT_UNWRAP’
   ASSERT_UNWRAP(info[0], obj, CryptoSecretstreamXchacha20poly1305StateWrap)
   ^
../src/macros.h:123:60: note: candidates are:
   type* var = Nan::ObjectWrap::Unwrap<type>(name->ToObject());
                                                            ^
../binding.cc:1258:3: note: in expansion of macro ‘ASSERT_UNWRAP’
   ASSERT_UNWRAP(info[0], obj, CryptoSecretstreamXchacha20poly1305StateWrap)
   ^
In file included from /root/.node-gyp/12.4.0/include/node/node.h:63:0,
                 from ../binding.cc:1:
/root/.node-gyp/12.4.0/include/node/v8.h:2532:44: note: v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^
/root/.node-gyp/12.4.0/include/node/v8.h:2532:44: note:   candidate expects 1 argument, 0 provided
In file included from /root/.node-gyp/12.4.0/include/node/v8-internal.h:14:0,
                 from /root/.node-gyp/12.4.0/include/node/v8.h:25,
                 from /root/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../binding.cc:1:
/root/.node-gyp/12.4.0/include/node/v8.h:2546:35: note: v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^
/root/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^
/root/.node-gyp/12.4.0/include/node/v8.h:2546:35: note:   candidate expects 1 argument, 0 provided
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^
/root/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^
make: *** [Release/obj.target/sodium/binding.o] Error 1
make: Leaving directory `/var/www-host/blockchain-authority-stellar/node_modules/sodium-native/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 3.10.0-957.1.3.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www-host/blockchain-authority-stellar/node_modules/sodium-native
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN stellar-pg@1.4.0 No description
npm WARN stellar-pg@1.4.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sodium-native@2.4.2 (node_modules/sodium-native):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sodium-native@2.4.2 install: `node-gyp-build "node preinstall.js" "node postinstall.js"`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

audited 94 packages in 47.232s
found 0 vulnerabilities
```

**Comment by emilbayes** [comment]
See #95 :)
