### ISSUE TITLE
Can't compile 2.4.4-2.4.6 (latest) on Windows/Node12

### ISSUE THREAD

**Issue by leofidus** [holepunchto/sodium-native#110]
When trying to start a project with the lastest sodium-native version I get the following error

```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  binding.cc
  crypto_hash_sha256_wrap.cc
  crypto_hash_sha512_wrap.cc
  crypto_generichash_wrap.cc
  crypto_onetimeauth_wrap.cc
  crypto_stream_xor_wrap.cc
  crypto_stream_chacha20_xor_wrap.cc
  crypto_secretstream_xchacha20poly1305_state_wrap.cc
  crypto_pwhash_async.cc
  crypto_pwhash_str_async.cc
  crypto_pwhash_str_verify_async.cc
  crypto_pwhash_scryptsalsa208sha256_async.cc
c:\users\Some User\source\vipfy-desktop\node_modules\sodium-native\libsodium\src\libsodium\include\sodium.h(5): fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory (compiling source file ..\src\crypto_pwhash_async.cc) [C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native\build\sodium.vcxproj]
c:\users\Some User\source\vipfy-desktop\node_modules\sodium-native\libsodium\src\libsodium\include\sodium.h(5): fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory (compiling source file ..\src\crypto_stream_chacha20_xor_wrap.cc) [C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native\build\sodium.vcxproj]
c:\users\Some User\source\vipfy-desktop\node_modules\sodium-native\libsodium\src\libsodium\include\sodium.h(5): fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory (compiling source file ..\src\crypto_generichash_wrap.cc) [C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native\build\sodium.vcxproj]
c:\users\Some User\source\vipfy-desktop\node_modules\sodium-native\libsodium\src\libsodium\include\sodium.h(5): fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory (compiling source file ..\src\crypto_stream_xor_wrap.cc) [C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native\build\sodium.vcxproj]
c:\users\Some User\source\vipfy-desktop\node_modules\sodium-native\libsodium\src\libsodium\include\sodium.h(5): fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory (compiling source file ..\src\crypto_onetimeauth_wrap.cc) [C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native\build\sodium.vcxproj]
c:\users\Some User\source\vipfy-desktop\node_modules\sodium-native\libsodium\src\libsodium\include\sodium.h(5): fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory (compiling source file ..\src\crypto_hash_sha512_wrap.cc) [C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native\build\sodium.vcxproj]
c:\users\Some User\source\vipfy-desktop\node_modules\sodium-native\libsodium\src\libsodium\include\sodium.h(5): fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory (compiling source file ..\src\crypto_pwhash_str_verify_async.cc) [C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native\build\sodium.vcxproj]
c:\users\Some User\source\vipfy-desktop\node_modules\sodium-native\libsodium\src\libsodium\include\sodium.h(5): fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory (compiling source file ..\src\crypto_pwhash_scryptsalsa208sha256_async.cc) [C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native\build\sodium.vcxproj]
c:\users\Some User\source\vipfy-desktop\node_modules\sodium-native\libsodium\src\libsodium\include\sodium.h(5): fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory (compiling source file ..\src\crypto_pwhash_str_async.cc) [C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native\build\sodium.vcxproj]
c:\users\Some User\source\vipfy-desktop\node_modules\sodium-native\libsodium\src\libsodium\include\sodium.h(5): fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory (compiling source file ..\src\crypto_secretstream_xchacha20poly1305_state_wrap.cc) [C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native\build\sodium.vcxproj]
c:\users\Some User\source\vipfy-desktop\node_modules\sodium-native\libsodium\src\libsodium\include\sodium.h(5): fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory (compiling source file ..\src\crypto_hash_sha256_wrap.cc) [C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native\build\sodium.vcxproj]
c:\users\Some User\source\vipfy-desktop\node_modules\sodium-native\libsodium\src\libsodium\include\sodium.h(5): fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory (compiling source file ..\binding.cc) [C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native\build\sodium.vcxproj]
  crypto_pwhash_scryptsalsa208sha256_str_async.cc
  crypto_pwhash_scryptsalsa208sha256_str_verify_async.cc
  win_delay_load_hook.cc
c:\users\Some User\source\vipfy-desktop\node_modules\sodium-native\libsodium\src\libsodium\include\sodium.h(5): fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory (compiling source file ..\src\crypto_pwhash_scryptsalsa208sha256_str_async.cc) [C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native\build\sodium.vcxproj]
c:\users\Some User\source\vipfy-desktop\node_modules\sodium-native\libsodium\src\libsodium\include\sodium.h(5): fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory (compiling source file ..\src\crypto_pwhash_scryptsalsa208sha256_str_verify_async.cc) [C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native\build\sodium.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Some User\Source\vipfy-desktop\node_modules\electron-rebuild\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Some User\\Source\\vipfy-desktop\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=4.0.0" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native
gyp ERR! node -v v12.7.0
gyp ERR! node-gyp -v v4.0.0
gyp ERR! not ok 

Failed with exit code: 1
Error: Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  binding.cc
  crypto_hash_sha256_wrap.cc
  crypto_hash_sha512_wrap.cc
  crypto_generichash_wrap.cc
  crypto_onetimeauth_wrap.cc
  crypto_stream_xor_wrap.cc
  crypto_stream_chacha20_xor_wrap.cc
  crypto_secretstream_xchacha20poly1305_state_wrap.cc
  crypto_pwhash_async.cc
  crypto_pwhash_str_async.cc
  crypto_pwhash_str_verify_async.cc
  crypto_pwhash_scryptsalsa208sha256_async.cc
c:\users\Some User\source\vipfy-desktop\node_modules\sodium-native\libsodium\src\libsodium\include\sodium.h(5): fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory (compiling source file ..\src\crypto_pwhash_async.cc) [C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native\build\sodium.vcxproj]
c:\users\Some User\source\vipfy-desktop\node_modules\sodium-native\libsodium\src\libsodium\include\sodium.h(5): fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory (compiling source file ..\src\crypto_stream_chacha20_xor_wrap.cc) [C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native\build\sodium.vcxproj]
c:\users\Some User\source\vipfy-desktop\node_modules\sodium-native\libsodium\src\libsodium\include\sodium.h(5): fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory (compiling source file ..\src\crypto_generichash_wrap.cc) [C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native\build\sodium.vcxproj]
c:\users\Some User\source\vipfy-desktop\node_modules\sodium-native\libsodium\src\libsodium\include\sodium.h(5): fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory (compiling source file ..\src\crypto_stream_xor_wrap.cc) [C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native\build\sodium.vcxproj]
c:\users\Some User\source\vipfy-desktop\node_modules\sodium-native\libsodium\src\libsodium\include\sodium.h(5): fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory (compiling source file ..\src\crypto_onetimeauth_wrap.cc) [C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native\build\sodium.vcxproj]
c:\users\Some User\source\vipfy-desktop\node_modules\sodium-native\libsodium\src\libsodium\include\sodium.h(5): fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory (compiling source file ..\src\crypto_hash_sha512_wrap.cc) [C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native\build\sodium.vcxproj]
c:\users\Some User\source\vipfy-desktop\node_modules\sodium-native\libsodium\src\libsodium\include\sodium.h(5): fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory (compiling source file ..\src\crypto_pwhash_str_verify_async.cc) [C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native\build\sodium.vcxproj]
c:\users\Some User\source\vipfy-desktop\node_modules\sodium-native\libsodium\src\libsodium\include\sodium.h(5): fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory (compiling source file ..\src\crypto_pwhash_scryptsalsa208sha256_async.cc) [C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native\build\sodium.vcxproj]
c:\users\Some User\source\vipfy-desktop\node_modules\sodium-native\libsodium\src\libsodium\include\sodium.h(5): fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory (compiling source file ..\src\crypto_pwhash_str_async.cc) [C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native\build\sodium.vcxproj]
c:\users\Some User\source\vipfy-desktop\node_modules\sodium-native\libsodium\src\libsodium\include\sodium.h(5): fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory (compiling source file ..\src\crypto_secretstream_xchacha20poly1305_state_wrap.cc) [C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native\build\sodium.vcxproj]
c:\users\Some User\source\vipfy-desktop\node_modules\sodium-native\libsodium\src\libsodium\include\sodium.h(5): fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory (compiling source file ..\src\crypto_hash_sha256_wrap.cc) [C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native\build\sodium.vcxproj]
c:\users\Some User\source\vipfy-desktop\node_modules\sodium-native\libsodium\src\libsodium\include\sodium.h(5): fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory (compiling source file ..\binding.cc) [C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native\build\sodium.vcxproj]
  crypto_pwhash_scryptsalsa208sha256_str_async.cc
  crypto_pwhash_scryptsalsa208sha256_str_verify_async.cc
  win_delay_load_hook.cc
c:\users\Some User\source\vipfy-desktop\node_modules\sodium-native\libsodium\src\libsodium\include\sodium.h(5): fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory (compiling source file ..\src\crypto_pwhash_scryptsalsa208sha256_str_async.cc) [C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native\build\sodium.vcxproj]
c:\users\Some User\source\vipfy-desktop\node_modules\sodium-native\libsodium\src\libsodium\include\sodium.h(5): fatal error C1083: Cannot open include file: 'sodium/version.h': No such file or directory (compiling source file ..\src\crypto_pwhash_scryptsalsa208sha256_str_verify_async.cc) [C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native\build\sodium.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Some User\Source\vipfy-desktop\node_modules\electron-rebuild\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Some User\\Source\\vipfy-desktop\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=4.0.0" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd C:\Users\Some User\Source\vipfy-desktop\node_modules\sodium-native
gyp ERR! node -v v12.7.0
gyp ERR! node-gyp -v v4.0.0
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (C:\Users\Some User\Source\vipfy-desktop\node_modules\electron-rebuild\node_modules\spawn-rx\src\index.ts:296:18)
    at SafeSubscriber.__tryOrUnsub (C:\Users\Some User\Source\vipfy-desktop\node_modules\electron-rebuild\node_modules\rxjs\src\internal\Subscriber.ts:265:10)
    at SafeSubscriber.error (C:\Users\Some User\Source\vipfy-desktop\node_modules\electron-rebuild\node_modules\rxjs\src\internal\Subscriber.ts:220:16)
    at Subscriber._error (C:\Users\Some User\Source\vipfy-desktop\node_modules\electron-rebuild\node_modules\rxjs\src\internal\Subscriber.ts:143:22)
    at Subscriber.error (C:\Users\Some User\Source\vipfy-desktop\node_modules\electron-rebuild\node_modules\rxjs\src\internal\Subscriber.ts:113:12)
    at MapSubscriber.Subscriber._error (C:\Users\Some User\Source\vipfy-desktop\node_modules\electron-rebuild\node_modules\rxjs\src\internal\Subscriber.ts:143:22)
    at MapSubscriber.Subscriber.error (C:\Users\Some User\Source\vipfy-desktop\node_modules\electron-rebuild\node_modules\rxjs\src\internal\Subscriber.ts:113:12)
    at SafeSubscriber._next (C:\Users\Some User\Source\vipfy-desktop\node_modules\electron-rebuild\node_modules\spawn-rx\src\index.ts:265:42)
    at SafeSubscriber.__tryOrUnsub (C:\Users\Some User\Source\vipfy-desktop\node_modules\electron-rebuild\node_modules\rxjs\src\internal\Subscriber.ts:265:10)
    at SafeSubscriber.next (C:\Users\Some User\Source\vipfy-desktop\node_modules\electron-rebuild\node_modules\rxjs\src\internal\Subscriber.ts:207:14)
    at Subscriber._next (C:\Users\Some User\Source\vipfy-desktop\node_modules\electron-rebuild\node_modules\rxjs\src\internal\Subscriber.ts:139:22)
    at Subscriber.next (C:\Users\Some User\Source\vipfy-desktop\node_modules\electron-rebuild\node_modules\rxjs\src\internal\Subscriber.ts:99:12)
    at DefaultIfEmptySubscriber._next (C:\Users\Some User\Source\vipfy-desktop\node_modules\electron-rebuild\node_modules\rxjs\src\internal\operators\defaultIfEmpty.ts:75:22)
    at DefaultIfEmptySubscriber.Subscriber.next (C:\Users\Some User\Source\vipfy-desktop\node_modules\electron-rebuild\node_modules\rxjs\src\internal\Subscriber.ts:99:12)
    at TakeLastSubscriber._complete (C:\Users\Some User\Source\vipfy-desktop\node_modules\electron-rebuild\node_modules\rxjs\src\internal\operators\takeLast.ts:108:21)
    at TakeLastSubscriber.Subscriber.complete (C:\Users\Some User\Source\vipfy-desktop\node_modules\electron-rebuild\node_modules\rxjs\src\internal\Subscriber.ts:126:12)
```

node_modules\sodium-native\libsodium\src\libsodium\include\sodium\ indeed doesn't contain a version.h, only version.h.in.

2.4.5 seems to suffer the same issue while the problem with 2.4.4 seems unrelated. Downgrading to 2.4.3 solves the problem.

**Comment by emilbayes** [comment]
@leofidus can you provide more info on your setup? Ideally this module shouldn't compile as it comes with prebuilds. Also our CI is green for most windows/node versions: https://travis-ci.org/sodium-friends/sodium-native/builds/569247402

And our Canary In The Gold Mine (citgm) is not reporting any errors or triggering any compilation: https://github.com/sodium-friends/sodium-native-citgm

**Comment by leofidus** [comment]
It's an electron app, so while the base system runs node 12 the actual code is used in Electron 4.0, which uses node 10.11.0.

Something somewhere probably triggers the rebuild because npm installs node 12 code and the actual app requires node 10 code, so it just calls gyp to recompile everything. At least that's what I assume, I haven't really dug into who's calling gyp.

**Comment by emilbayes** [comment]
Npm install actually comes with prebuilds for those versions as well but electrons rebuild always messes it up. The citgm actually also covers latest versions of electron without triggering rebuilds (ie it’s a supported target)

**Comment by emilbayes** [comment]
Closing for now as this seems to be a electron-builder issue
