### ISSUE TITLE
issue installing unrecognized command line option "-std=gnu++1y"

### ISSUE THREAD

**Issue by ochampet** [holepunchto/sodium-native#112]
npm install sodium-native

I have installed in my local account gcc 7.3.0  and I have set LD_LIBRARY_PATH and LD_RUN_PATH to the location of my local gcc. However, I'm still getting the below error.  Is there a parameter I need to pass for node or the sodium package to use the gcc 7.3.0.
This is a CENTOS local account that has gcc 4.4.

 CXX(target) Release/obj.target/sodium/binding.o
cc1plus: error: unrecognized command line option "-std=gnu++1y"
make: *** [Release/obj.target/sodium/binding.o] Error 1
make: Leaving directory `/home/mylocal/api/node_modules/sodium-native/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/emedappc/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 2.6.32-954.3.5.lve1.4.59.el6.x86_64
gyp ERR! command "/home/mylocal/.nvm/versions/node/v10.16.3/bin/node" "/home/mylocal/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mylocal/api/node_modules/sodium-native
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by ochampet** [comment]
I figure out my issue to install it using a local gcc copy 
env CC=/local/path/gcc-7.3.0-install/bin/gcc CXX=/local/path/gcc-7.3.0-install/bin/g++ npm install sodium-native

then to run node app.js
I had to use 
export LD_LIBRARY_PATH=/local/path/gcc-7.3.0-install/lib/:/local/path/gcc-7.3.0-install/lib64
