### ISSUE TITLE
Install fails on node 13

### ISSUE THREAD

**Issue by Powersource** [holepunchto/sodium-native#117]
I'm guessing this is related to https://github.com/sodium-friends/sodium-native/issues/116 and/or https://github.com/sodium-friends/sodium-native/pull/114

```
...
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/me/prj/web/sodium-native/libsodium/src'
make[2]: Leaving directory '/home/me/prj/web/sodium-native/libsodium/src'
make[1]: Leaving directory '/home/me/prj/web/sodium-native/libsodium/src'
Making install in test
make[1]: Entering directory '/home/me/prj/web/sodium-native/libsodium/test'
Making install in default
make[2]: Entering directory '/home/me/prj/web/sodium-native/libsodium/test/default'
make[3]: Entering directory '/home/me/prj/web/sodium-native/libsodium/test/default'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/me/prj/web/sodium-native/libsodium/test/default'
make[2]: Leaving directory '/home/me/prj/web/sodium-native/libsodium/test/default'
make[2]: Entering directory '/home/me/prj/web/sodium-native/libsodium/test'
make[3]: Entering directory '/home/me/prj/web/sodium-native/libsodium/test'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/me/prj/web/sodium-native/libsodium/test'
make[2]: Leaving directory '/home/me/prj/web/sodium-native/libsodium/test'
make[1]: Leaving directory '/home/me/prj/web/sodium-native/libsodium/test'
make[1]: Entering directory '/home/me/prj/web/sodium-native/libsodium'
make[2]: Entering directory '/home/me/prj/web/sodium-native/libsodium'
make[2]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/home/me/prj/web/sodium-native/tmp/lib/pkgconfig'
 /usr/bin/install -c -m 644 libsodium.pc '/home/me/prj/web/sodium-native/tmp/lib/pkgconfig'
make[2]: Leaving directory '/home/me/prj/web/sodium-native/libsodium'
make[1]: Leaving directory '/home/me/prj/web/sodium-native/libsodium'
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack TypeError: Class constructor Range cannot be invoked without 'new'
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/node-gyp/lib/find-python.js:229:28)
gyp ERR! stack     at PythonFinder.execFileCallback (/usr/lib/node_modules/node-gyp/lib/find-python.js:274:7)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:7)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1028:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:443:11)
gyp ERR! stack     at Socket.emit (events.js:321:20)
gyp ERR! stack     at Pipe.<anonymous> (net.js:668:12)
gyp ERR! System Linux 5.4.8-arch1-1
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/me/prj/web/sodium-native
gyp ERR! node -v v13.6.0
gyp ERR! node-gyp -v v6.0.1
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! sodium-native@2.4.6 install: `node-gyp-build "node preinstall.js" "node postinstall.js"`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the sodium-native@2.4.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/me/.npm/_logs/2020-01-08T21_23_55_493Z-debug.log
```

Running node 13.6.0 and npm 6.13.4

**Comment by emilbayes** [comment]
We are make a new build now :)

**Comment by mafintosh** [comment]
works on 13
