### ISSUE TITLE
Invalid 'sig' length throws "invalid 'm' length" error

### ISSUE THREAD

**Issue by christianbundy** [holepunchto/sodium-native#129]
Hi! I might be misunderstanding something, but I think this error message might be wrong. Just build from the latest commit (39c521bb28a9f03a092dd9115270a0535a748c9d) and I can confirm that this problem still exists. Am I holding it wrong?

```javascript
const sodium = require('sodium-native')

const sig = Buffer.alloc(sodium.crypto_sign_BYTES - 1) // Wrong number of bytes!
const m = Buffer.from('hello world')
const pk = Buffer.alloc(sodium.crypto_sign_PUBLICKEYBYTES)
const bool = sodium.crypto_sign_verify_detached(sig, m, pk)
```

```
/home/christianbundy/src/sodium-native/test.js:6
const bool = sodium.crypto_sign_verify_detached(sig, m, pk)
                    ^

Error: "m" must be at least crypto_sign_BYTES bytes long
    at Object.<anonymous> (/home/christianbundy/src/sodium-native/test.js:6:21)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

In case it's useful:

```console
$ npm version
{
  'sodium-native': '3.1.1',
  npm: '6.14.5',
  ares: '1.16.1',
  brotli: '1.0.7',
  cldr: '37.0',
  http_parser: '2.9.3',
  icu: '67.1',
  llhttp: '2.0.4',
  modules: '72',
  napi: '6',
  nghttp2: '1.40.0',
  node: '12.17.0',
  openssl: '1.1.1g',
  tz: '2019c',
  unicode: '13.0',
  uv: '1.37.0',
  v8: '7.8.279.23-node.37',
  zlib: '1.2.11'
}
```

**Comment by emilbayes** [comment]
Yeah that looks like a typo here:
https://github.com/sodium-friends/sodium-native/blob/39c521bb28a9f03a092dd9115270a0535a748c9d/binding.c#L367

**Comment by christianbundy** [comment]
Oh thanks, I tried grepping around but couldn't find that string. I'll make a PR. :tada:

**Comment by emilbayes** [comment]
Thanks! Merged :) Will come out next time we do a release
