### ISSUE TITLE
Install fails on node 14

### ISSUE THREAD

**Issue by ariwbolton** [holepunchto/sodium-native#136]
I tried to install v2.4.9 and v3.2.0 using node 14.11.0, but I'm getting this error for both versions during `npm install sodium-native`:

```
> sodium-native@2.4.9 install /Users/me/Documents/tmp/node_modules/other-package/node_modules/sodium-native
> node-gyp-build "node preinstall.js" "node postinstall.js"

libtool is required, but wasn't found on this system
./configure: line 5: ./configure: No such file or directory
/Users/me/Documents/tmp/node_modules/other-package/node_modules/sodium-native/preinstall.js:119
    if (err) throw err
             ^

Error: ./configure exited with 127
    at ChildProcess.<anonymous> (/Users/ari/Documents/tmp/node_modules/other-package/node_modules/sodium-native/preinstall.js:149:25)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium-native@2.4.9 install: `node-gyp-build "node preinstall.js" "node postinstall.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium-native@2.4.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2020-09-18T00_16_58_814Z-debug.log
```

Installing both versions using node 12 works fine; I suspect support for node 14 just hasn't been added yet. (Unless the intent is for users to now install `libtool` manually before installing `sodium-native` -- I haven't tried that, but I'm hoping to avoid that if possible)

**Comment by mixmix** [comment]
from memory you might need https://www.npmjs.com/package/node-gyp installed globally, and if you follow the install of that closely I think you might find yourself installing `libtool`??

**Comment by mixmix** [comment]
oh also note I think you only need these build tools in place if it couldn't find an existing prebuilt binary matching your system setup. That might be why you didn't hit this in the past

**Comment by gre** [comment]
Should there be some prebuilds on sodium-native to solve this situation? Experiencing same issue

**Comment by mafintosh** [comment]
There should be prebuilds and I run it daily (and many others as well on mac). Can you share a bit more about the system you are seeing failures on?

**Comment by gre** [comment]
System **Mac OS Big Sur 11.4**

```
uname -a
Darwin LMFR0019 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

node -v
v14.17.1
```

How I experience an issue: mostly through stellar-sdk, would it be because they use an outdate version then?

```
➜  foo yarn add stellar-sdk
yarn add v1.22.10
warning ../package.json: No license field
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
warning Error running install script for optional dependency: "/Users/grenaudeau/Desktop/foo/node_modules/sodium-native: Command failed.
Exit code: 1
Command: node-gyp-build \"node preinstall.js\" \"node postinstall.js\"
Arguments:
Directory: /Users/grenaudeau/Desktop/foo/node_modules/sodium-native
Output:
automake is required, but wasn't found on this system
./configure: line 5: ./configure: No such file or directory
/Users/grenaudeau/Desktop/foo/node_modules/sodium-native/preinstall.js:119
    if (err) throw err
             ^

Error: ./configure exited with 127
    at ChildProcess.<anonymous> (/Users/grenaudeau/Desktop/foo/node_modules/sodium-native/preinstall.js:149:25)
    at ChildProcess.emit (events.js:375:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)"
info This module is OPTIONAL, you can safely ignore this error
success Saved lockfile.
success Saved 32 new dependencies.
```


```
yarn list sodium-native
└─ sodium-native@2.4.9
```

if you confirm it's because it's outdated, i'll directly contact stellar-sdk team. Thanks.

**Comment by gre** [comment]
Ok nevermind, I think it's more on stellar-sdk side now. Sorry for noise. https://github.com/stellar/js-stellar-base/issues/404
