### ISSUE TITLE
install fails with npm 7

### ISSUE THREAD

**Issue by ungoldman** [holepunchto/sodium-native#142]
On node v12.16.3, upgraded from npm 6.14.11 to latest 7.5.3, then removed `node_modules` and ran `npm install` in a large project to test installation.

Got the following output:

```
npm ERR! code 1
npm ERR! path /Users/ng/dev/work/sho/api/node_modules/sodium-native
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! CXX(target) Release/obj.target/sodium/binding.o
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@12.16.3 | darwin | x64
npm ERR! gyp info find Python using Python version 3.7.4 found at "/usr/local/opt/python/bin/python3.7"
npm ERR! gyp info spawn /usr/local/opt/python/bin/python3.7
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/ng/.nvm/versions/node/v12.16.3/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/ng/dev/work/sho/api/node_modules/sodium-native/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/ng/.nvm/versions/node/v12.16.3/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/ng/Library/Caches/node-gyp/12.16.3/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/ng/Library/Caches/node-gyp/12.16.3',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/ng/.nvm/versions/node/v12.16.3/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/ng/Library/Caches/node-gyp/12.16.3/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/ng/dev/work/sho/api/node_modules/sodium-native',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../binding.cc:4:
npm ERR! ../libsodium/src/libsodium/include/sodium.h:5:10: fatal error: 'sodium/version.h' file not found
npm ERR! #include "sodium/version.h"
npm ERR!          ^~~~~~~~~~~~~~~~~~
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/sodium/binding.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/ng/.nvm/versions/node/v12.16.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
npm ERR! gyp ERR! System Darwin 18.7.0
npm ERR! gyp ERR! command "/Users/ng/.nvm/versions/node/v12.16.3/bin/node" "/Users/ng/.nvm/versions/node/v12.16.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/ng/dev/work/sho/api/node_modules/sodium-native
npm ERR! gyp ERR! node -v v12.16.3
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ng/.npm/_logs/2021-02-10T18_07_36_583Z-debug.log
```

Reverting back to npm 6, installation works fine again.

**Comment by mafintosh** [comment]
Does it use the prebuild on 6 or also compile?

**Comment by ungoldman** [comment]
not sure! this is the only related output I see for 6:

```
> sodium-native@2.4.9 install /Users/ng/dev/work/sho/api/node_modules/sodium-native
> node-gyp-build "node preinstall.js" "node postinstall.js"
```

Happy to dig deeper if you can point out where to look.

I'm on an older macOS version if that helps -- Mojave 10.14.6. I don't _think_ that should matter for compile OS/arch etc.

**Comment by ungoldman** [comment]
Just an update here -- a colleague with an environment similar to mine tried to repro and had no problems. So I tried to repro the above error again as a sanity check -- and had no problems. I haven't restarted (same terminal session as a few hours ago even), so I am at a loss as to why it failed that time but not this time. It's possible there's a race condition in npm's code... or some weird environmental thing in my local setup.

Either way for now since I'm unable to reproduce my own issue I'm closing this. If anyone comes across this problem again, I would suggest trying it a second time and seeing what happens. If the issue persists, we can reopen and try to pin down why it's happening.
