### ISSUE TITLE
pwhash issue

### ISSUE THREAD

**Issue by emilbayes** [holepunchto/sodium-native#19]
Doing the following:

```js
var sodium = require('sodium-native')

var output = Buffer.alloc(sodium.crypto_pwhash_STRBYTES)
var passwd = new Buffer('Hej, Verden!')
var opslimit = 3
var memlimit = 1 << 12

sodium.crypto_pwhash_str(output, passwd, opslimit, memlimit)
```

I get:

```
/sodium-native/example.js:8
sodium.crypto_pwhash_str(output, passwd, opslimit, memlimit)
       ^

Error: Sodium operation failed
    at Error (native)
    at Object.<anonymous> (/sodium-native/example.js:8:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
```

But doing:

```js
var sodium = require('sodium-native')

var output = Buffer.alloc(sodium.crypto_pwhash_STRBYTES)
var passwd = new Buffer('Hej, Verden!')
var opslimit = 3
var memlimit = 1 << 12 + 1

sodium.crypto_pwhash_str(output, passwd, opslimit, memlimit)
```

Everything runs fine. This is in opposition to `sodium.crypto_pwhash_MEMLIMIT_MIN` being `1`. I don't know if this is our fault or a libsodium issue

**Comment by emilbayes** [comment]
This is fixed upstream, but yet to be released: https://github.com/jedisct1/libsodium/commit/4568b74cc8905e77fe1938de1796634abff3e273

**Comment by mafintosh** [comment]
fixed in master
