### ISSUE TITLE
No native build was found for platform=darwin arch=x64 runtime=node abi=108 uv=1 libc=glibc node=18.5.0

### ISSUE THREAD

**Issue by rohitcodergroww** [holepunchto/sodium-native#195]
Any solution or recommendation for this issue?

```
➜ backend git:(main) ✗ ./backend                                               
Error while starting Fastify port Error: No native build was found for platform=darwin arch=x64 runtime=node abi=108 uv=1 libc=glibc node=18.5.0
    loaded from: /snapshot/backend/node_modules/sodium-native

    at Function.<anonymous> (/snapshot/backend/node_modules/node-gyp-build/node-gyp-build.js:60:9)
    at load (/snapshot/backend/node_modules/node-gyp-build/node-gyp-build.js:22:30)
    at Object.<anonymous> (/snapshot/backend/node_modules/sodium-native/index.js:1:101)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
```

**Comment by mafintosh** [comment]
Which version of sodium-native are you trying to install?

**Comment by rohitcodergroww** [comment]
Hi @mafintosh,

Thanks for replying, actually this was being used by one other dep, and after seeing your msg, i checked transitive deps version, and i found it was using old sodium-native, and i upgrade that dep to latest, which is using latest sodium-native.

Thanks for giving me hint :) 

Problem solved! :)

**Comment by mafintosh** [comment]
not my first rodeo, awesome you got it working
