### ISSUE TITLE
4.2.1 breaks Alpine support

### ISSUE THREAD

**Issue by JulianBerger** [holepunchto/sodium-native#202]
Since 4.2.1 i get this error:

`Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /app/node_modules/sodium-native/prebuilds/linux-x64/sodium-native.node)`

Downgrading to 4.2.0 fixes the issue.

**Comment by kasperisager** [comment]
v4.2.1 was compiled using CMake and https://github.com/holepunchto/cmake-napi, not `node-gyp`, so that most likely has an effect. What I'm wondering is _which_.

Which OS are you running?

**Comment by kasperisager** [comment]
Everything is still integrated against both macOS, Ubuntu, and Windows, so Linux support is by no means broken in general.

**Comment by JulianBerger** [comment]
I run node:20-alpine inside Docker. I resolved the error by installing glibc support (running `apk add gcompat`). Now it runs fine. But I think the switch to cmake should be a major update because this change is likely to impact many CI pipelines.

**Comment by kasperisager** [comment]
Gotcha, so this is specifically about Alpine and musl. Pushing this out as a new major would certainly have been a disservice to those using Alpine as they'd then be stuck on the previous major, so I suggest we work towards a fix instead.

@mafintosh I imagine this worked previously by virtue of `node-gyp-build` compiling the bindings from source when running on a system using musl?

**Comment by mafintosh** [comment]
Sometimes it worked ya but was a mess. @JulianBerger stay in 4.2.0 for now or cd node_modules/sodium-native and call bare-dev install —node —force post install. We are working on a tool that streamlines this across all our native repos

**Comment by kasperisager** [comment]
@JulianBerger Could you try this tool: https://www.npmjs.com/package/bare-prebuild. It'll compile all native addons in `node_modules` from source:

```console
npm i -g bare-prebuild
npm i sodium-native
bare-prebuild
```

**Comment by kasperisager** [comment]
@JulianBerger I'm actually able to load latest `sodium-native` on Alpine just fine. I traced it to https://github.com/holepunchto/sodium-native/pull/207, so that likely did the trick.

**Comment by meyfa** [comment]
It's unfortunately still broken for me. `npm ls` confirms `sodium-native@4.3.1`.

```
node:internal/modules/cjs/loader:1586
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /app/node_modules/sodium-native/prebuilds/linux-x64/sodium-native.node)
    at Module._extensions..node (node:internal/modules/cjs/loader:1586:18)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at load (/app/node_modules/node-gyp-build/node-gyp-build.js:22:10)
    at Object.<anonymous> (/app/node_modules/sodium-native/index.js:1:43)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v20.18.1
```

Building for `linux/amd64` on alpine.

**Comment by kasperisager** [comment]
I've confirmed that the `x64` build still references `ld-linux-x86-64.so`, specifically the `__tls_get_addr` symbol.

**Comment by kasperisager** [comment]
`libsodium` uses thread-local storage here: https://github.com/jedisct1/libsodium/blob/985ad65bfb1563ca69e0bc0248e15da4f5cf575f/src/libsodium/randombytes/internal/randombytes_internal_random.c#L142-L145

I'm unsure if there's a way to avoid referencing the dynamic linker. To maintain Alpine compatibility, the builds are only allowed to reference `libc`.

@mafintosh FYI.

**Comment by mafintosh** [comment]
Sounds like an issue for libsodium itself?

**Comment by kasperisager** [comment]
There's most likely not much we can do on our end, no.

**Comment by meyfa** [comment]
> There's most likely not much we can do on our end, no.

Sorry that I probably missed something... but wasn't the change from 4.2.0 to 4.2.1 only to the build system, meaning the libsodium code itself didn't cause any issues previously, until something inside this repo changed?

**Comment by kasperisager** [comment]
`libsodium` was updated as well.

**Comment by kasperisager** [comment]
Yes, the only change from 4.2.0 to 4.2.1 was https://github.com/holepunchto/sodium-native/pull/200, which switched the build system from `node-gyp` to CMake.

Previously, the module worked on Alpine by virtue of https://www.npmjs.com/package/node-gyp-build attempting to compile fresh prebuilds during `npm install`. This is turn only worked by virtue of the module shipping all the necessary bits for source compilation, including the full `libsodium` sources. With the switch to CMake, the module only ships a build definition, the binding sources, and prebuilds for the targets it explicitly supports.

You can use https://www.npmjs.com/package/bare-prebuild to compile fresh prebuilds specifically for your own hardware.

**Comment by jhrncar** [comment]
As of today, on v. 4.3.1 still broken on my node:20-alpine

**Comment by kasperisager** [comment]
It'll stay broken for as long as `libsodium` references the dynamic linker. The fix is to compile prebuilds specifically for your target system using https://github.com/holepunchto/bare-prebuild. I've shipped musl toolchains in https://github.com/holepunchto/cmake-toolchains today to make the process easier:

```console
bare-prebuild --arch arm64|x64 --environment musl
```

You can run the above from any Linux machine with a musl cross-compiler for the target system available in its `$PATH`.

**Comment by kasperisager** [comment]
I've released prebuilt musl toolchains as well: https://github.com/holepunchto/musl-toolchains/releases/tag/v1.2.5

**Comment by openscript** [comment]
@kasperisager Thank you for providing a solution. Unfortunately I don't know how to apply it to a multi arch Docker image. What would be the steps to create such?

**Comment by kasperisager** [comment]
Pleasure! You most likely want to use a [multi-stage build](https://docs.docker.com/build/building/multi-stage/) where you do something like this:

1.  Start off with a Ubuntu base image with Node.js installed.
2.  Install your dependencies, which will install our default `sodium-native` prebuilds for the GNU C library.
3.  Install `bare-prebuild`.
4.  Fetch a musl toolchain from https://github.com/holepunchto/musl-toolchains/releases.
5.  Compile new prebuilds for your dependencies, including `sodium-native`, using `bare-prebuild`:
    ```console
    bare-prebuild --arch arm64|x64 --environment musl
    ```
6.  Switch to an Alpine base image with Node.js installed
7.  Copy over the dependencies from the Ubuntu image.

**Comment by dennemark** [comment]
Quite a bummer. Maybe this will help: https://github.com/jedisct1/libsodium/discussions/1449

**Comment by dennemark** [comment]
Now I understand the issue better.
Wouldnt it be possible to have the musl version prebuild in sodium-native? seems like sodium-native is not compatible with alpine, but libsodium is.

**Comment by openscript** [comment]
> Now I understand the issue better. Wouldnt it be possible to have the musl version prebuild in sodium-native? seems like sodium-native is not compatible with alpine, but libsodium is.

I've added a PR implementing this.
