### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by dominictarr** [holepunchto/sodium-native#4]
npm install gave me this error:
```
make: *** No rule to make target 'Release/obj.target/libsodium/deps/libsodium/src/libsodium/crypto_scalarmult/curve25519/sandy2x/consts.o', needed by 'Release/obj.target/deps/sodium.a'.  Stop.
make: Leaving directory '/home/dominic/c/sodium-native/build'
prebuild ERR! build error 
prebuild ERR! stack Error: `make` failed with exit code: 2
prebuild ERR! stack     at ChildProcess.onExit (/home/dominic/c/sodium-native/node_modules/node-gyp/lib/build.js:276:23)
prebuild ERR! stack     at emitTwo (events.js:106:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:191:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
prebuild ERR! not ok 
prebuild ERR! build Error: `make` failed with exit code: 2
prebuild ERR! build     at ChildProcess.onExit (/home/dominic/c/sodium-native/node_modules/node-gyp/lib/build.js:276:23)
prebuild ERR! build     at emitTwo (events.js:106:13)
prebuild ERR! build     at ChildProcess.emit (events.js:191:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_p
```

**Comment by mafintosh** [comment]
I'm trying to debug that right now actually. I need to figure out how to get gyp to compile the assembly files on linux.

**Comment by mafintosh** [comment]
Okay, master should build now. There is a bug in crypto_stream where it is missing a symbol but the rest should work

**Comment by mafintosh** [comment]
Was running autogen.sh which apparently you shouldn't do on releases. Fixed in master now.

**Comment by mafintosh** [comment]
builds on travis as well now
