### ISSUE TITLE
Unable to compile on any platform (issue shared with other NodeJS bindings)

### ISSUE THREAD

**Issue by pzduniak** [holepunchto/sodium-native#43]
```  CC       sodium/libsodium_la-utils.lo
  CC       sodium/libsodium_la-version.lo
  CC       randombytes/salsa20/libsodium_la-randombytes_salsa20_random.lo
  CC       randombytes/sysrandom/libsodium_la-randombytes_sysrandom.lo
  CC       crypto_scalarmult/curve25519/donna_c64/libsodium_la-curve25519_donna_c64.lo
make[3]: *** No rule to make target 'crypto_stream/salsa20/xmm6/salsa20_xmm6-asm.S', needed by 'crypto_stream/salsa20/xmm6/libsodium_la-salsa20_xmm6-asm.lo'.  Stop.
make[3]: Leaving directory '/app/node_modules/sodium-native/libsodium/src/libsodium'
make[2]: Leaving directory '/app/node_modules/sodium-native/libsodium/src/libsodium'
make[2]: *** [Makefile:2925: install-recursive] Error 1
make[1]: *** [Makefile:397: install-recursive] Error 1
make[1]: Leaving directory '/app/node_modules/sodium-native/libsodium/src'
make: *** [Makefile:511: install-recursive] Error 1
/app/node_modules/sodium-native/preinstall.js:93
        if (err) throw err
                 ^

Error: make exited with 2
    at ChildProcess.<anonymous> (/app/node_modules/sodium-native/preinstall.js:129:25)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

I can compile libsodium-stable though, so I'm not sure what's up with that.

**Comment by mafintosh** [comment]
which system are you on?

**Comment by pzduniak** [comment]
Anything running in Docker. Debian Jessie, Alpine, everything results in the same error.

**Comment by pzduniak** [comment]
https://github.com/jedisct1/libsodium/issues/633 is where I was told to actually try compiling it alone and it builds successfully. That has no use for me though.

**Comment by jedisct1** [comment]
@mafintosh Looks like npm packages don't include `.S` files (and maybe other file types).

**Comment by mafintosh** [comment]
@pzduniak which version of sodium-native are you trying to install? have a feeling this is ~1.0 based on @jedisct1's comment

**Comment by emilbayes** [comment]
Just tried with the following Dockerfile, and it worked fine

```dockerfile
FROM debian:jessie

RUN apt-get update
RUN apt-get install curl
RUN curl -fs https://raw.githubusercontent.com/mafintosh/node-install/master/install | sh
RUN node-install 8.5.0

# Latest
RUN npm install sodium-native
RUN node -p "var s = require('sodium-native'); var b = Buffer.alloc(10); s.randombytes_buf(b); b"

RUN rm -rf node_modules

# Older version
RUN npm install sodium-native@1
RUN node -p "var s = require('sodium-native'); var b = Buffer.alloc(10); s.randombytes_buf(b); b"
```

**Comment by emilbayes** [comment]
However I was not able to get the following to work (got stuck at `configure: error: C compiler cannot create executables`): 

```Dockerfile
FROM alpine:latest

RUN apk update
RUN apk add nodejs libtool automake gcc
RUN npm install sodium-native
```

**Comment by emilbayes** [comment]
Just confirmed that the `*.S` files are missing, and it seems to be an issue with `.npmignore` which falls back to `.gitignore`, and `npm` seems to use the case-sensitivity of the filesystem, unlike `git`.

**Comment by MylesBorins** [comment]
This might have been responsible for the failures we were seeing in CITGM as well. We had removed sodium-native, but we can add it back if this fixes the issues
