### ISSUE TITLE
crash error using with Electron 3 on MacOS

### ISSUE THREAD

**Issue by k2s** [holepunchto/sodium-native#89]
Electron 2 works, but when upgrading to Electron 3 I get this crash error:

```
Code Type:             X86-64 (Native)
OS Version:            Mac OS X 10.14.3 (18D42)

Dyld Error Message:
  Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Volumes/*/x.app/Contents/Resources/app.asar.unpacked/node_modules/sodium-native/prebuilds/darwin-x64/electron-64.node
  Expected in: flat namespace
```

**Comment by emilbayes** [comment]
@k2s Do you know which function you called and from which process? What I get from demangling the symbol is `_v8::FunctionTemplate::New(v8::Isolate*, void (*)(v8::FunctionCallbackInfo<v8::Value> const&), v8::Local<v8::Value>, v8::Local<v8::Signature>, int, v8::ConstructorBehavior, v8::SideEffectType)`

**Comment by k2s** [comment]
@emilbayes the only line in index.js of my test project is `require('sodium-native')` and I get that error.

my package.json:
```
{
  "name": "x",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "electron": "3.0.0",
    "electron-builder": "^20.38.5"
  },
  "dependencies": {
    "sodium-native": "^2.2.5"
  },
  "scripts": {
    "start": "electron .",
    "dist": "build"
  },
  "build": {
    "appId": "com.example.test",
    "mac": {
      "target": "dmg"
    }
  }
}
``` 

and I run `yarn run dist` to build the app

**Comment by emilbayes** [comment]
@k2s Have you seen this? https://github.com/lgeiger/node-abi/issues/54
It seems that there's a mismatch with the ABI version that electron 3 needs and the one that it reports. Can you upgrade to electron 4?

**Comment by k2s** [comment]
@emilbayes Erro on run of the same project, but Electron upgraded to 4.0.4:

```
Uncaught Exception:
Error: No native build was found for runtime=electron abi=69 platform=darwinglibc arch=x64
    at Function.load.path (/Volumes/x 1.0.0/x.app/Contents/Resources/app.asar/node_modules/node-gyp-build/index.js:56:9)
    at load (/Volumes/x 1.0.0/x.app/Contents/Resources/app.asar/node_modules/node-gyp-build/index.js:18:30)
    at Object.<anonymous> (/Volumes/x 1.0.0/x.app/Contents/Resources/app.asar/node_modules/sodium-native/index.js:1:194)
    at Object.<anonymous> (/Volumes/x 1.0.0/x.app/Contents/Resources/app.asar/node_modules/sodium-native/index.js:5:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
```

**Comment by emilbayes** [comment]
@k2s So that one there is no prebuilt for because the issue was just resolved as I wrote the previous message :) I think you can use something like `electron-rebuild` to make a new build for 4.0.4

**Comment by emilbayes** [comment]
`sodium-native@2.2.6` works with `electron@4.0.4`
